export * from './db-add-patrimony-factory'
export * from './db-check-patrimony-by-id-factory'
export * from './db-update-patrimony-factory'
export * from './db-delete-patrimony-factory'
export * from './db-load-patrimonies-factory'
