export * from './load-patrimony-by-owner-id'
export * from './add-patrimony'
export * from './check-patrimony-by-id'
export * from './update-patrimony'
export * from './delete-patrimony'
export * from './load-patrimonies'
export * from './load-patrimony-by-id'
