export * from './add-patrimony-postgres'
export * from './update-patrimony-postgres'
export * from './delete-patrimony-postgres'
export * from './load-patrimonies-postgres'
export * from './load-patrimony-by-id-postgres'
export * from './load-patrimony-by-number-postgres'
